FROM ubuntu:20.04

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip && \
  pip3 install \
    pip-tools \
    setuptools \
    wheel && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV PYTHONPATH /opt/optimor/src
WORKDIR /opt/optimor/src
COPY ./requirements_test.txt requirements_test.txt
RUN pip-sync requirements_test.txt
