name: Continuous Integration Tests
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the lint container
        run: docker-compose build lint
      - name: Check linting
        run: docker-compose run --rm lint
